[package]
name = "arca-pkg-model"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
description = "manifest.toml y modelos de paquete"

[dependencies]
arca-types = { path = "../L0-arca-types" }
serde = { workspace = true }
semver = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
