[package]
name = "arca-tools-pk"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
description = "CLI pack/verify/sign .arca (lado Deepin)"

[dependencies]
arca-7z = { path = "../L0-arca-7z" }
arca-pkg-model = { path = "../L0-arca-pkg-model" }
arca-sign = { path = "../L0-arca-sign", features = ["signer"] }
arca-types = { path = "../L0-arca-types" }
clap = { workspace = true }
semver = { workspace = true }
sevenz-rust2 = { workspace = true }
sha2 = "0.10"
walkdir = "2"

[dev-dependencies]
arca-installer = { path = "../L1-arca-installer" }
arca-store = { path = "../L1-arca-store" }
tempfile = { workspace = true }
